repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: []
        args: ["--ignore-missing-imports", "--no-warn-unused-ignores"]
  - repo: local
    hooks:
      - id: forbid-virtualenv-commits
        name: Forbid committed virtualenv or site-packages
        entry: bash
        language: system
        pass_filenames: false
        args:
          - -c
          - |
              if git diff --cached --name-only \
                | grep -Eq '^(\.venv/|venv/|env/|.*site-packages)'; then
                echo 'Error: virtualenv artifacts staged; remove before committing.'
                exit 1
              fi
              exit 0
      - id: forbid-large-binaries
        name: Forbid >5MB binary blobs (except patches)
        entry: bash
        language: system
        pass_filenames: false
        args:
          - -c
          - |
              status=0
              while read -r f; do
                if [ -f "$f" ]; then
                  sz=$(wc -c < "$f")
                  if [ "$sz" -gt 5000000 ]; then
                    echo "Large file blocked ($f, $sz bytes). Use Git LFS or exclude."
                    status=1
                  fi
                fi
              done < <(git diff --cached --name-only)
              exit "$status"
