name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]
      - name: Run tests
        run: pytest -q

  minimal-no-dsp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install (core only, no extras)
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Verify THD mode is stub
        run: |
          MODE=$(python unified_gui_layout.py thd-mode)
          echo "Mode=$MODE"
          if [ "$MODE" != "stub" ]; then echo "Expected stub mode without dsp extra" && exit 1; fi
      - name: Run tests (should auto-skip advanced path parts)
        run: pytest -q

  build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build distributions
        run: |
          python -m pip install --upgrade pip build
          python -m build
          ls -l dist
      - name: Install wheel
        run: |
          WHEEL=$(ls dist/*.whl | head -n1)
          python -m pip install "$WHEEL"
      - name: Smoke test import & version
        run: |
          python - <<'PY'
import amp_benchkit, importlib
print('version:', amp_benchkit.__version__)
import unified_gui_layout as ugl
print('thd-mode:', 'advanced' if hasattr(ugl, 'thd_fft') else 'missing')
PY
