name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system deps (alsa, xvfb minimal)
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev xvfb

      - name: Install package with test & dev extras
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test,dev]
          pip install mypy ruff

      - name: Run tests with coverage
        run: pytest -q --cov=amp_benchkit --cov-report=term-missing --cov-report=xml

      - name: Upload coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml

      - name: Ruff lint
        run: ruff check .

      - name: Mypy type check (allow incomplete)
        run: mypy --ignore-missing-imports amp_benchkit || true

      - name: Smoke selftest CLI
        run: |
          python unified_gui_layout.py --selftest --headless || true
