name: Codex Auto-Fix (on CI failure)

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  codex_autofix:
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_repository.full_name == github.repository }}
    runs-on: ubuntu-latest
    env:
      FAILED_WORKFLOW: ${{ github.event.workflow_run.name }}
      FAILED_URL: ${{ github.event.workflow_run.html_url }}
      FAILED_BRANCH: ${{ github.event.workflow_run.head_branch }}
      FAILED_SHA: ${{ github.event.workflow_run.head_sha }}

    steps:
      - name: Checkout the failing commit
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Try tests locally (non-blocking)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test,dev]
          pytest -q || true
          ruff check . || true
          mypy --ignore-missing-imports amp_benchkit || true

      - name: Run Codex to fix the failure
        id: run_codex
        uses: openai/codex-action@v1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          sandbox: workspace-write
          prompt: |
            Repo: ${{ github.repository }}
            Branch: ${{ env.FAILED_BRANCH }}
            CI URL: ${{ env.FAILED_URL }}
            Commit: ${{ env.FAILED_SHA }}

            Task: Investigate why the CI named "${{ env.FAILED_WORKFLOW }}" failed and make the minimal, safe code changes to fix it.
            Context: amp-benchkit is a Python project. The CI runs pytest with coverage, ruff, and mypy (allow incomplete).
            Steps:
              1) Run tests and linters locally.
              2) Read error output, identify the root cause.
              3) Modify code and/or tests to fix the failure.
              4) Re-run checks locally to confirm green.
              5) Write a concise commit message describing the fix.

      - name: Create a PR with Codex’s changes
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Codex auto-fix for failing CI on '${{ env.FAILED_BRANCH }}'"
          body: |
            This PR was created automatically after CI failed.

            - Workflow: **${{ env.FAILED_WORKFLOW }}**
            - Run: ${{ env.FAILED_URL }}
            - Commit: ${{ env.FAILED_SHA }}

            Please review the changes generated by Codex.
          branch: codex/autofix-${{ env.FAILED_BRANCH }}
          branch-suffix: short-commit-hash
          base: ${{ env.FAILED_BRANCH }}
