name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install .[publish]
      - name: Build distributions
        run: |
          python -m build --sdist --wheel
      - name: Verify metadata
        run: |
          python -m twine check dist/*
      - name: Publish to PyPI
        if: secrets.PYPI_API_TOKEN != ''
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --non-interactive dist/*
      - name: Skip notice
        if: secrets.PYPI_API_TOKEN == ''
        run: echo "PYPI_API_TOKEN not set; skipping upload."