name: Publish (TestPyPI RC)

on:
  push:
    tags:
      - 'v*-rc*'

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build
        run: python -m build --sdist --wheel

      - name: Twine check
        run: twine check dist/*

      - name: Publish to TestPyPI
        if: success()
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
        run: |
          if [ -z "${TWINE_PASSWORD}" ]; then
            echo "TESTPYPI_API_TOKEN not set; skipping upload.";
            exit 0;
          fi
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
